export const BEFORE_PURCHASE = 'BEFORE_PURCHASE';
export const DURING_PURCHASE = 'DURING_PURCHASE';
export const TICKS_READY = 'TICKS_READY';
export const PROPOSALS_READY = 'PROPOSALS_READY';
export const PURCHASE_SUCCESSFUL = 'PURCHASE_SUCCESSFUL';
export const OPEN_CONTRACT = 'OPEN_CONTRACT';
export const SOLD = 'SOLD';
export const INVALID_ACTION = 'INVALID_ACTION';
